---

- name: Download Logstash package
  become: yes
  get_url:
    dest: "/usr/local/src/logstash-{{ sansible_logstash_version }}_all.deb"
    url: "https://download.elastic.co/logstash/logstash/packages/debian/logstash-{{ sansible_logstash_version }}_all.deb"

- name: Install Logstash
  become: yes
  apt:
    deb: "/usr/local/src/logstash-{{ sansible_logstash_version }}_all.deb"
    state: present
