---

- name: "Install 2.x Family"
  include: install/2.x.yml
  when: logstash.family == '2.0'

- name: Install 5.x Family
  include: install/5.x.yml
  when: logstash.family == '5.x'

- name: Enable logstash service
  become: yes
  service:
    name: logstash
    enabled: yes
  notify:
    - start logstash
